### ISSUE TITLE
Environment variables don't effective

### ISSUE THREAD

**Issue by ettwz** [telepresenceio/telepresence#669]
I use telepresence to replace a spring-boot program that running on kubernetes. 

I defined a variable in `application.yml`. Like this:

```yaml
test:
  value: test
```

And than overwrite it through `deployment.yaml` on kubernetes. Like this:

```yaml
    spec:
      containers:
      - env:
        - name: TEST_VALUE
          value: FOOBAR
```
And here is my shell command: 

```shell
telepresence \
--swap-deployment spring-boot-simple-server \
--docker-run \
--rm \
-v$(pwd):/build \
-p 8080:8080 \
maven:3.5.3-jdk-8-slim mvn -f /build spring-boot:run
```

But the value of this variable havn't overwrited in my local program that start by telepresence (the value of "test.value" is "test").

I execd into this pod and than used `env` command to get system environment variables. The `TEST_VALUE` is already defind in system environment variables. But java application hasn't read it.

OSX platform don't have this problem. The variable that overwrite in deployment is effectived in java applicaton which start by telepresence .

Is that a bug or I make something wrong?

Thanks.

**Comment by ark3** [comment]
Once your Telepresence session is running there is a Telepresence proxy pod in the cluster and a local Docker container running your application. You said you were able to see the correct environment variable value when you used `kubectl exec ... env` to access the pod. Can you see whether the local container has the correct environment variable setting too? Something like `docker exec -it <container name> env`? 

Thanks for your help.

**Comment by jody-frankowski** [comment]
If you are on Linux and telepresence calls docker with `sudo` you won't have the environment variables when doing `--swap-deployment`. I just noticed this and I actually had to patch telepresence to call docker with `sudo -E`.

**Comment by ark3** [comment]
@ettwz Does telepresence use `sudo docker` on your system? If so, then fixing #672 will solve this problem for you.

```
$ egrep "Launching.*docker" telepresence.log 
  30.7 TEL | [54] Launching: docker run --rm --privileged --name=telepresence-1527875302-983097-97670 datawire/telepresence-local:0.88 proxy '{"port": 55343, "cidrs": ["10.3.240.0/20", "10.0.2.0/24", "10.0.1.0/24", "10.0.0.0/24", "10.0.19.0/24"], "expose_ports": [], "ip": "198.18.0.254"}'
$ # No sudo docker on my mac
```

@jody-frankowski: Thanks for finding this bug!

**Comment by ettwz** [comment]
@jody-frankowski  thank you. This works for me. I add my user to docker group.

**Comment by jody-frankowski** [comment]
@ettwz You should know that by adding yourself to the docker group, you're effectively giving your user root permissions https://security.stackexchange.com/questions/178542/is-adding-docker-group-not-a-good-idea

**Comment by mderazon** [comment]
> fixing #672 will solve this problem for you.
@ark3 was this solved ? Because I think I am still hitting this problem

``` sh
$ telepresence --namespace ns --swap-deployment myservice --expose 9020 --run env | grep SECRET
```
This will print `env` SECRET variable correctly but

``` sh
$ telepresence --namespace ns --swap-deployment myservice --expose 9020 --run echo $SECRET
```
Weirdly does not print the `SECRET` variable

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

$ telepresence --version
0.101
```

**Comment by ark3** [comment]
Yes, this was fixed, as you can see from your first example. Your second example doesn't work because your shell expands `$SECRET` before it launches Telepresence. You can see this in action by putting `echo` at the beginning of your command.

```console
$ echo telepresence --run echo before $KUBERNETES_PORT after
telepresence --run echo before after
```

To grab an environment variable like that, you'll need single quotes and a shell invocation (at least for Bash). Perhaps something like this:

```console
$ telepresence --run sh -c 'echo $KUBERNETES_PORT'
T: [...]
T: Setup complete. Launching your command.
tcp://10.3.240.1:443
T: Your process has exited.
T: [...]
```

**Comment by mderazon** [comment]
Thanks for the explanation.
Indeed running
``` sh
$ telepresence --namespace ns --swap-deployment myservice --expose 9020 --run sh -c 'echo $SECRET'
```
like you suggested expands the environment variable correctly.

However I was debugging this due to some issue of my node.js program not reading the SECRET env var correctly when running
```sh
$ telepresence --namespace stark-uc --swap-deployment idp --expose 9020 --run sh -c 'npm start'
```
That still doesn't work.
I must be doing something wrong
